- name: Ruby | Adds .gemrc
  action: copy src=gemrc dest=~{{ ruby_deploy_user }}/.gemrc owner={{ ruby_deploy_user }} group={{ ruby_deploy_user }} mode=0750
  tags:
    - ruby
    - ruby:config
    - config

