- name: Ruby | Checks if target ruby is installed
  shell: bash -lc "rbenv versions | grep {{ version }}"
  register: ruby_is_installed
  ignore_errors: true
  tags:
    - ruby
    - ruby:install
    - install

- name: Ruby | Installs ruby
  action: shell cd; bash -lc "rbenv install {{ version }}"
  when: ruby_is_installed|failed
  # Takes no more than 600 secs on a small VM
  async: 600
  poll: 30
  tags:
    - ruby
    - ruby:install
    - install

