---
- name: ensure repo exists at {{ deploy_path }}
  stat: path={{ deploy_path }}
  register: app_path

- fail: msg="Webapp repo was not synced to the server/VM"
  when: app_path.stat.isdir is not defined or app_path.stat.isdir == false

- debug: msg="bundle update in dir {{ deploy_path }}"

- shell: whoami

- shell: echo $PATH

# TODO: move this to capistrano?
- name: bundle update
  command: "{{ ruby_bin }}/bundle update chdir={{ deploy_path }}"

# glob not working correctly
#- name: clear cached pages
#  shell: rm {{ deploy_path }}/public/**/*.html

- name: precompile assets
  shell: "RAILS_ENV=production {{ ruby_bin }}/bundle exec rake assets:precompile chdir={{ deploy_path }}"

- name: is unicorn running
  shell: ps aux | grep "unicorn_rails master" | grep -v grep
  register: unicorn_running
  ignore_errors: yes

- name: HUP unicorn
  command: pkill -HUP -f "unicorn_rails master"
  when: unicorn_running|success

- name: find unicorn
  command: "/home/vagrant/.rbenv/bin/rbenv which unicorn_rails"
  register: unicorn_bin

- name: start unicorn
  # TODO: this isn't going to return, run it as daemon
  # somehow or actually look into capistrano
  shell: "RAILS_ENV=production {{ unicorn_bin.stdout }} -c unicorn.conf chdir={{ deploy_path }}"
